/**
 * The Batch 2 owner photographs (2026-10-10), as hashed asset URLs.
 *
 * GENERATED by scripts/gen-batch2-photo-module.mjs — do not hand-edit. Add a
 * photograph to that script's PHOTOS list and to the BATCH2 ladder in
 * scripts/gen-hero-images.mjs, then re-run both.
 *
 * Imported rather than referenced by path so Vite fingerprints the files, which
 * is what makes vercel.json's immutable year-long image cache safe on them.
 *
 * Each export is a plain object literal over explicit imports, deliberately:
 * an `import.meta.glob` lookup table cannot be tree-shaken, so every page
 * would carry the URL of every photograph on the site. This way a page pays
 * only for the pictures it actually shows.
 *
 * `width`/`height` are the intrinsic pixels of the top variant. In the
 * gallery slot the image is cropped to a fixed box by `object-cover`, so these
 * do not set the rendered shape — they stop the page reflowing when the image
 * lands, which is CLS.
 */

export interface Photo {
  /** Largest JPEG — the <img> fallback where WebP is not taken. */
  src: string;
  /** WebP candidates — the `srcSet` on the <img>. */
  srcSet: string;
  /** AVIF candidates — offered first, through a <source>. */
  avifSrcSet: string;
  width: number;
  height: number;
}

import redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc400Avif from '@/assets/red-oak-stump-five-feet-wide-before-grinding-jacksonville-nc-400.avif';
import redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc400Webp from '@/assets/red-oak-stump-five-feet-wide-before-grinding-jacksonville-nc-400.webp';
import redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc400Jpg from '@/assets/red-oak-stump-five-feet-wide-before-grinding-jacksonville-nc-400.jpg';
import redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc640Avif from '@/assets/red-oak-stump-five-feet-wide-before-grinding-jacksonville-nc-640.avif';
import redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc640Webp from '@/assets/red-oak-stump-five-feet-wide-before-grinding-jacksonville-nc-640.webp';
import redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc640Jpg from '@/assets/red-oak-stump-five-feet-wide-before-grinding-jacksonville-nc-640.jpg';
import redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc800Avif from '@/assets/red-oak-stump-five-feet-wide-before-grinding-jacksonville-nc-800.avif';
import redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc800Webp from '@/assets/red-oak-stump-five-feet-wide-before-grinding-jacksonville-nc-800.webp';
import redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc800Jpg from '@/assets/red-oak-stump-five-feet-wide-before-grinding-jacksonville-nc-800.jpg';
import redOakStumpGrindingRootChasingJacksonvilleNc400Avif from '@/assets/red-oak-stump-grinding-root-chasing-jacksonville-nc-400.avif';
import redOakStumpGrindingRootChasingJacksonvilleNc400Webp from '@/assets/red-oak-stump-grinding-root-chasing-jacksonville-nc-400.webp';
import redOakStumpGrindingRootChasingJacksonvilleNc400Jpg from '@/assets/red-oak-stump-grinding-root-chasing-jacksonville-nc-400.jpg';
import redOakStumpGrindingRootChasingJacksonvilleNc640Avif from '@/assets/red-oak-stump-grinding-root-chasing-jacksonville-nc-640.avif';
import redOakStumpGrindingRootChasingJacksonvilleNc640Webp from '@/assets/red-oak-stump-grinding-root-chasing-jacksonville-nc-640.webp';
import redOakStumpGrindingRootChasingJacksonvilleNc640Jpg from '@/assets/red-oak-stump-grinding-root-chasing-jacksonville-nc-640.jpg';
import redOakStumpGrindingRootChasingJacksonvilleNc800Avif from '@/assets/red-oak-stump-grinding-root-chasing-jacksonville-nc-800.avif';
import redOakStumpGrindingRootChasingJacksonvilleNc800Webp from '@/assets/red-oak-stump-grinding-root-chasing-jacksonville-nc-800.webp';
import redOakStumpGrindingRootChasingJacksonvilleNc800Jpg from '@/assets/red-oak-stump-grinding-root-chasing-jacksonville-nc-800.jpg';
import resistographTraceWaterOakHeartwoodRotJacksonvilleNc480Avif from '@/assets/resistograph-trace-water-oak-heartwood-rot-jacksonville-nc-480.avif';
import resistographTraceWaterOakHeartwoodRotJacksonvilleNc480Webp from '@/assets/resistograph-trace-water-oak-heartwood-rot-jacksonville-nc-480.webp';
import resistographTraceWaterOakHeartwoodRotJacksonvilleNc480Jpg from '@/assets/resistograph-trace-water-oak-heartwood-rot-jacksonville-nc-480.jpg';
import resistographTraceWaterOakHeartwoodRotJacksonvilleNc768Avif from '@/assets/resistograph-trace-water-oak-heartwood-rot-jacksonville-nc-768.avif';
import resistographTraceWaterOakHeartwoodRotJacksonvilleNc768Webp from '@/assets/resistograph-trace-water-oak-heartwood-rot-jacksonville-nc-768.webp';
import resistographTraceWaterOakHeartwoodRotJacksonvilleNc768Jpg from '@/assets/resistograph-trace-water-oak-heartwood-rot-jacksonville-nc-768.jpg';
import resistographTraceWaterOakHeartwoodRotJacksonvilleNc1024Avif from '@/assets/resistograph-trace-water-oak-heartwood-rot-jacksonville-nc-1024.avif';
import resistographTraceWaterOakHeartwoodRotJacksonvilleNc1024Webp from '@/assets/resistograph-trace-water-oak-heartwood-rot-jacksonville-nc-1024.webp';
import resistographTraceWaterOakHeartwoodRotJacksonvilleNc1024Jpg from '@/assets/resistograph-trace-water-oak-heartwood-rot-jacksonville-nc-1024.jpg';
import resistographTracePenForScaleJacksonvilleNc480Avif from '@/assets/resistograph-trace-pen-for-scale-jacksonville-nc-480.avif';
import resistographTracePenForScaleJacksonvilleNc480Webp from '@/assets/resistograph-trace-pen-for-scale-jacksonville-nc-480.webp';
import resistographTracePenForScaleJacksonvilleNc480Jpg from '@/assets/resistograph-trace-pen-for-scale-jacksonville-nc-480.jpg';
import resistographTracePenForScaleJacksonvilleNc768Avif from '@/assets/resistograph-trace-pen-for-scale-jacksonville-nc-768.avif';
import resistographTracePenForScaleJacksonvilleNc768Webp from '@/assets/resistograph-trace-pen-for-scale-jacksonville-nc-768.webp';
import resistographTracePenForScaleJacksonvilleNc768Jpg from '@/assets/resistograph-trace-pen-for-scale-jacksonville-nc-768.jpg';
import resistographTracePenForScaleJacksonvilleNc1024Avif from '@/assets/resistograph-trace-pen-for-scale-jacksonville-nc-1024.avif';
import resistographTracePenForScaleJacksonvilleNc1024Webp from '@/assets/resistograph-trace-pen-for-scale-jacksonville-nc-1024.webp';
import resistographTracePenForScaleJacksonvilleNc1024Jpg from '@/assets/resistograph-trace-pen-for-scale-jacksonville-nc-1024.jpg';
import southernPineBeetlePitchTubesOnslowCountyNc400Avif from '@/assets/southern-pine-beetle-pitch-tubes-onslow-county-nc-400.avif';
import southernPineBeetlePitchTubesOnslowCountyNc400Webp from '@/assets/southern-pine-beetle-pitch-tubes-onslow-county-nc-400.webp';
import southernPineBeetlePitchTubesOnslowCountyNc400Jpg from '@/assets/southern-pine-beetle-pitch-tubes-onslow-county-nc-400.jpg';
import southernPineBeetlePitchTubesOnslowCountyNc600Avif from '@/assets/southern-pine-beetle-pitch-tubes-onslow-county-nc-600.avif';
import southernPineBeetlePitchTubesOnslowCountyNc600Webp from '@/assets/southern-pine-beetle-pitch-tubes-onslow-county-nc-600.webp';
import southernPineBeetlePitchTubesOnslowCountyNc600Jpg from '@/assets/southern-pine-beetle-pitch-tubes-onslow-county-nc-600.jpg';
import windCrackedPineLimbOverHouseRichlandsNc400Avif from '@/assets/wind-cracked-pine-limb-over-house-richlands-nc-400.avif';
import windCrackedPineLimbOverHouseRichlandsNc400Webp from '@/assets/wind-cracked-pine-limb-over-house-richlands-nc-400.webp';
import windCrackedPineLimbOverHouseRichlandsNc400Jpg from '@/assets/wind-cracked-pine-limb-over-house-richlands-nc-400.jpg';
import windCrackedPineLimbOverHouseRichlandsNc640Avif from '@/assets/wind-cracked-pine-limb-over-house-richlands-nc-640.avif';
import windCrackedPineLimbOverHouseRichlandsNc640Webp from '@/assets/wind-cracked-pine-limb-over-house-richlands-nc-640.webp';
import windCrackedPineLimbOverHouseRichlandsNc640Jpg from '@/assets/wind-cracked-pine-limb-over-house-richlands-nc-640.jpg';
import windCrackedPineLimbOverHouseRichlandsNc800Avif from '@/assets/wind-cracked-pine-limb-over-house-richlands-nc-800.avif';
import windCrackedPineLimbOverHouseRichlandsNc800Webp from '@/assets/wind-cracked-pine-limb-over-house-richlands-nc-800.webp';
import windCrackedPineLimbOverHouseRichlandsNc800Jpg from '@/assets/wind-cracked-pine-limb-over-house-richlands-nc-800.jpg';
import crackedPineLimbCanopyInspectionRichlandsNc400Avif from '@/assets/cracked-pine-limb-canopy-inspection-richlands-nc-400.avif';
import crackedPineLimbCanopyInspectionRichlandsNc400Webp from '@/assets/cracked-pine-limb-canopy-inspection-richlands-nc-400.webp';
import crackedPineLimbCanopyInspectionRichlandsNc400Jpg from '@/assets/cracked-pine-limb-canopy-inspection-richlands-nc-400.jpg';
import crackedPineLimbCanopyInspectionRichlandsNc640Avif from '@/assets/cracked-pine-limb-canopy-inspection-richlands-nc-640.avif';
import crackedPineLimbCanopyInspectionRichlandsNc640Webp from '@/assets/cracked-pine-limb-canopy-inspection-richlands-nc-640.webp';
import crackedPineLimbCanopyInspectionRichlandsNc640Jpg from '@/assets/cracked-pine-limb-canopy-inspection-richlands-nc-640.jpg';
import crackedPineLimbCanopyInspectionRichlandsNc800Avif from '@/assets/cracked-pine-limb-canopy-inspection-richlands-nc-800.avif';
import crackedPineLimbCanopyInspectionRichlandsNc800Webp from '@/assets/cracked-pine-limb-canopy-inspection-richlands-nc-800.webp';
import crackedPineLimbCanopyInspectionRichlandsNc800Jpg from '@/assets/cracked-pine-limb-canopy-inspection-richlands-nc-800.jpg';
import heartwoodRotHollowOakTrunkSurfCityNc400Avif from '@/assets/heartwood-rot-hollow-oak-trunk-surf-city-nc-400.avif';
import heartwoodRotHollowOakTrunkSurfCityNc400Webp from '@/assets/heartwood-rot-hollow-oak-trunk-surf-city-nc-400.webp';
import heartwoodRotHollowOakTrunkSurfCityNc400Jpg from '@/assets/heartwood-rot-hollow-oak-trunk-surf-city-nc-400.jpg';
import heartwoodRotHollowOakTrunkSurfCityNc640Avif from '@/assets/heartwood-rot-hollow-oak-trunk-surf-city-nc-640.avif';
import heartwoodRotHollowOakTrunkSurfCityNc640Webp from '@/assets/heartwood-rot-hollow-oak-trunk-surf-city-nc-640.webp';
import heartwoodRotHollowOakTrunkSurfCityNc640Jpg from '@/assets/heartwood-rot-hollow-oak-trunk-surf-city-nc-640.jpg';
import heartwoodRotHollowOakTrunkSurfCityNc800Avif from '@/assets/heartwood-rot-hollow-oak-trunk-surf-city-nc-800.avif';
import heartwoodRotHollowOakTrunkSurfCityNc800Webp from '@/assets/heartwood-rot-hollow-oak-trunk-surf-city-nc-800.webp';
import heartwoodRotHollowOakTrunkSurfCityNc800Jpg from '@/assets/heartwood-rot-hollow-oak-trunk-surf-city-nc-800.jpg';
import heartwoodRotOakStumpSurfCityNc400Avif from '@/assets/heartwood-rot-oak-stump-surf-city-nc-400.avif';
import heartwoodRotOakStumpSurfCityNc400Webp from '@/assets/heartwood-rot-oak-stump-surf-city-nc-400.webp';
import heartwoodRotOakStumpSurfCityNc400Jpg from '@/assets/heartwood-rot-oak-stump-surf-city-nc-400.jpg';
import heartwoodRotOakStumpSurfCityNc640Avif from '@/assets/heartwood-rot-oak-stump-surf-city-nc-640.avif';
import heartwoodRotOakStumpSurfCityNc640Webp from '@/assets/heartwood-rot-oak-stump-surf-city-nc-640.webp';
import heartwoodRotOakStumpSurfCityNc640Jpg from '@/assets/heartwood-rot-oak-stump-surf-city-nc-640.jpg';
import heartwoodRotOakStumpSurfCityNc800Avif from '@/assets/heartwood-rot-oak-stump-surf-city-nc-800.avif';
import heartwoodRotOakStumpSurfCityNc800Webp from '@/assets/heartwood-rot-oak-stump-surf-city-nc-800.webp';
import heartwoodRotOakStumpSurfCityNc800Jpg from '@/assets/heartwood-rot-oak-stump-surf-city-nc-800.jpg';
import treeThroughBarnRoofBeulavilleNc400Avif from '@/assets/tree-through-barn-roof-beulaville-nc-400.avif';
import treeThroughBarnRoofBeulavilleNc400Webp from '@/assets/tree-through-barn-roof-beulaville-nc-400.webp';
import treeThroughBarnRoofBeulavilleNc400Jpg from '@/assets/tree-through-barn-roof-beulaville-nc-400.jpg';
import treeThroughBarnRoofBeulavilleNc640Avif from '@/assets/tree-through-barn-roof-beulaville-nc-640.avif';
import treeThroughBarnRoofBeulavilleNc640Webp from '@/assets/tree-through-barn-roof-beulaville-nc-640.webp';
import treeThroughBarnRoofBeulavilleNc640Jpg from '@/assets/tree-through-barn-roof-beulaville-nc-640.jpg';
import treeThroughBarnRoofBeulavilleNc800Avif from '@/assets/tree-through-barn-roof-beulaville-nc-800.avif';
import treeThroughBarnRoofBeulavilleNc800Webp from '@/assets/tree-through-barn-roof-beulaville-nc-800.webp';
import treeThroughBarnRoofBeulavilleNc800Jpg from '@/assets/tree-through-barn-roof-beulaville-nc-800.jpg';
import craneSetUpOverDamagedBarnBeulavilleNc400Avif from '@/assets/crane-set-up-over-damaged-barn-beulaville-nc-400.avif';
import craneSetUpOverDamagedBarnBeulavilleNc400Webp from '@/assets/crane-set-up-over-damaged-barn-beulaville-nc-400.webp';
import craneSetUpOverDamagedBarnBeulavilleNc400Jpg from '@/assets/crane-set-up-over-damaged-barn-beulaville-nc-400.jpg';
import craneSetUpOverDamagedBarnBeulavilleNc640Avif from '@/assets/crane-set-up-over-damaged-barn-beulaville-nc-640.avif';
import craneSetUpOverDamagedBarnBeulavilleNc640Webp from '@/assets/crane-set-up-over-damaged-barn-beulaville-nc-640.webp';
import craneSetUpOverDamagedBarnBeulavilleNc640Jpg from '@/assets/crane-set-up-over-damaged-barn-beulaville-nc-640.jpg';
import craneSetUpOverDamagedBarnBeulavilleNc800Avif from '@/assets/crane-set-up-over-damaged-barn-beulaville-nc-800.avif';
import craneSetUpOverDamagedBarnBeulavilleNc800Webp from '@/assets/crane-set-up-over-damaged-barn-beulaville-nc-800.webp';
import craneSetUpOverDamagedBarnBeulavilleNc800Jpg from '@/assets/crane-set-up-over-damaged-barn-beulaville-nc-800.jpg';
import climberInFallenTreeOnBarnBeulavilleNc400Avif from '@/assets/climber-in-fallen-tree-on-barn-beulaville-nc-400.avif';
import climberInFallenTreeOnBarnBeulavilleNc400Webp from '@/assets/climber-in-fallen-tree-on-barn-beulaville-nc-400.webp';
import climberInFallenTreeOnBarnBeulavilleNc400Jpg from '@/assets/climber-in-fallen-tree-on-barn-beulaville-nc-400.jpg';
import climberInFallenTreeOnBarnBeulavilleNc640Avif from '@/assets/climber-in-fallen-tree-on-barn-beulaville-nc-640.avif';
import climberInFallenTreeOnBarnBeulavilleNc640Webp from '@/assets/climber-in-fallen-tree-on-barn-beulaville-nc-640.webp';
import climberInFallenTreeOnBarnBeulavilleNc640Jpg from '@/assets/climber-in-fallen-tree-on-barn-beulaville-nc-640.jpg';
import climberInFallenTreeOnBarnBeulavilleNc800Avif from '@/assets/climber-in-fallen-tree-on-barn-beulaville-nc-800.avif';
import climberInFallenTreeOnBarnBeulavilleNc800Webp from '@/assets/climber-in-fallen-tree-on-barn-beulaville-nc-800.webp';
import climberInFallenTreeOnBarnBeulavilleNc800Jpg from '@/assets/climber-in-fallen-tree-on-barn-beulaville-nc-800.jpg';
import craneLiftingTreeSectionOffBarnBeulavilleNc400Avif from '@/assets/crane-lifting-tree-section-off-barn-beulaville-nc-400.avif';
import craneLiftingTreeSectionOffBarnBeulavilleNc400Webp from '@/assets/crane-lifting-tree-section-off-barn-beulaville-nc-400.webp';
import craneLiftingTreeSectionOffBarnBeulavilleNc400Jpg from '@/assets/crane-lifting-tree-section-off-barn-beulaville-nc-400.jpg';
import craneLiftingTreeSectionOffBarnBeulavilleNc640Avif from '@/assets/crane-lifting-tree-section-off-barn-beulaville-nc-640.avif';
import craneLiftingTreeSectionOffBarnBeulavilleNc640Webp from '@/assets/crane-lifting-tree-section-off-barn-beulaville-nc-640.webp';
import craneLiftingTreeSectionOffBarnBeulavilleNc640Jpg from '@/assets/crane-lifting-tree-section-off-barn-beulaville-nc-640.jpg';
import craneLiftingTreeSectionOffBarnBeulavilleNc800Avif from '@/assets/crane-lifting-tree-section-off-barn-beulaville-nc-800.avif';
import craneLiftingTreeSectionOffBarnBeulavilleNc800Webp from '@/assets/crane-lifting-tree-section-off-barn-beulaville-nc-800.webp';
import craneLiftingTreeSectionOffBarnBeulavilleNc800Jpg from '@/assets/crane-lifting-tree-section-off-barn-beulaville-nc-800.jpg';
import stormBrokenLimbHangingInCanopyOnslowCountyNc400Avif from '@/assets/storm-broken-limb-hanging-in-canopy-onslow-county-nc-400.avif';
import stormBrokenLimbHangingInCanopyOnslowCountyNc400Webp from '@/assets/storm-broken-limb-hanging-in-canopy-onslow-county-nc-400.webp';
import stormBrokenLimbHangingInCanopyOnslowCountyNc400Jpg from '@/assets/storm-broken-limb-hanging-in-canopy-onslow-county-nc-400.jpg';
import stormBrokenLimbHangingInCanopyOnslowCountyNc640Avif from '@/assets/storm-broken-limb-hanging-in-canopy-onslow-county-nc-640.avif';
import stormBrokenLimbHangingInCanopyOnslowCountyNc640Webp from '@/assets/storm-broken-limb-hanging-in-canopy-onslow-county-nc-640.webp';
import stormBrokenLimbHangingInCanopyOnslowCountyNc640Jpg from '@/assets/storm-broken-limb-hanging-in-canopy-onslow-county-nc-640.jpg';
import stormBrokenLimbHangingInCanopyOnslowCountyNc800Avif from '@/assets/storm-broken-limb-hanging-in-canopy-onslow-county-nc-800.avif';
import stormBrokenLimbHangingInCanopyOnslowCountyNc800Webp from '@/assets/storm-broken-limb-hanging-in-canopy-onslow-county-nc-800.webp';
import stormBrokenLimbHangingInCanopyOnslowCountyNc800Jpg from '@/assets/storm-broken-limb-hanging-in-canopy-onslow-county-nc-800.jpg';
import splitPineLimbInCanopyOnslowCountyNc400Avif from '@/assets/split-pine-limb-in-canopy-onslow-county-nc-400.avif';
import splitPineLimbInCanopyOnslowCountyNc400Webp from '@/assets/split-pine-limb-in-canopy-onslow-county-nc-400.webp';
import splitPineLimbInCanopyOnslowCountyNc400Jpg from '@/assets/split-pine-limb-in-canopy-onslow-county-nc-400.jpg';
import splitPineLimbInCanopyOnslowCountyNc640Avif from '@/assets/split-pine-limb-in-canopy-onslow-county-nc-640.avif';
import splitPineLimbInCanopyOnslowCountyNc640Webp from '@/assets/split-pine-limb-in-canopy-onslow-county-nc-640.webp';
import splitPineLimbInCanopyOnslowCountyNc640Jpg from '@/assets/split-pine-limb-in-canopy-onslow-county-nc-640.jpg';
import splitPineLimbInCanopyOnslowCountyNc800Avif from '@/assets/split-pine-limb-in-canopy-onslow-county-nc-800.avif';
import splitPineLimbInCanopyOnslowCountyNc800Webp from '@/assets/split-pine-limb-in-canopy-onslow-county-nc-800.webp';
import splitPineLimbInCanopyOnslowCountyNc800Jpg from '@/assets/split-pine-limb-in-canopy-onslow-county-nc-800.jpg';
import spiderLiftBoomExtendedToPineOnslowCountyNc400Avif from '@/assets/spider-lift-boom-extended-to-pine-onslow-county-nc-400.avif';
import spiderLiftBoomExtendedToPineOnslowCountyNc400Webp from '@/assets/spider-lift-boom-extended-to-pine-onslow-county-nc-400.webp';
import spiderLiftBoomExtendedToPineOnslowCountyNc400Jpg from '@/assets/spider-lift-boom-extended-to-pine-onslow-county-nc-400.jpg';
import spiderLiftBoomExtendedToPineOnslowCountyNc640Avif from '@/assets/spider-lift-boom-extended-to-pine-onslow-county-nc-640.avif';
import spiderLiftBoomExtendedToPineOnslowCountyNc640Webp from '@/assets/spider-lift-boom-extended-to-pine-onslow-county-nc-640.webp';
import spiderLiftBoomExtendedToPineOnslowCountyNc640Jpg from '@/assets/spider-lift-boom-extended-to-pine-onslow-county-nc-640.jpg';
import spiderLiftBoomExtendedToPineOnslowCountyNc800Avif from '@/assets/spider-lift-boom-extended-to-pine-onslow-county-nc-800.avif';
import spiderLiftBoomExtendedToPineOnslowCountyNc800Webp from '@/assets/spider-lift-boom-extended-to-pine-onslow-county-nc-800.webp';
import spiderLiftBoomExtendedToPineOnslowCountyNc800Jpg from '@/assets/spider-lift-boom-extended-to-pine-onslow-county-nc-800.jpg';
import spiderLiftTrackedBaseOnLawnOnslowCountyNc400Avif from '@/assets/spider-lift-tracked-base-on-lawn-onslow-county-nc-400.avif';
import spiderLiftTrackedBaseOnLawnOnslowCountyNc400Webp from '@/assets/spider-lift-tracked-base-on-lawn-onslow-county-nc-400.webp';
import spiderLiftTrackedBaseOnLawnOnslowCountyNc400Jpg from '@/assets/spider-lift-tracked-base-on-lawn-onslow-county-nc-400.jpg';
import spiderLiftTrackedBaseOnLawnOnslowCountyNc640Avif from '@/assets/spider-lift-tracked-base-on-lawn-onslow-county-nc-640.avif';
import spiderLiftTrackedBaseOnLawnOnslowCountyNc640Webp from '@/assets/spider-lift-tracked-base-on-lawn-onslow-county-nc-640.webp';
import spiderLiftTrackedBaseOnLawnOnslowCountyNc640Jpg from '@/assets/spider-lift-tracked-base-on-lawn-onslow-county-nc-640.jpg';
import spiderLiftTrackedBaseOnLawnOnslowCountyNc800Avif from '@/assets/spider-lift-tracked-base-on-lawn-onslow-county-nc-800.avif';
import spiderLiftTrackedBaseOnLawnOnslowCountyNc800Webp from '@/assets/spider-lift-tracked-base-on-lawn-onslow-county-nc-800.webp';
import spiderLiftTrackedBaseOnLawnOnslowCountyNc800Jpg from '@/assets/spider-lift-tracked-base-on-lawn-onslow-county-nc-800.jpg';
import lawnLeftUnruttedAfterLiftWorkOnslowCountyNc400Avif from '@/assets/lawn-left-unrutted-after-lift-work-onslow-county-nc-400.avif';
import lawnLeftUnruttedAfterLiftWorkOnslowCountyNc400Webp from '@/assets/lawn-left-unrutted-after-lift-work-onslow-county-nc-400.webp';
import lawnLeftUnruttedAfterLiftWorkOnslowCountyNc400Jpg from '@/assets/lawn-left-unrutted-after-lift-work-onslow-county-nc-400.jpg';
import lawnLeftUnruttedAfterLiftWorkOnslowCountyNc640Avif from '@/assets/lawn-left-unrutted-after-lift-work-onslow-county-nc-640.avif';
import lawnLeftUnruttedAfterLiftWorkOnslowCountyNc640Webp from '@/assets/lawn-left-unrutted-after-lift-work-onslow-county-nc-640.webp';
import lawnLeftUnruttedAfterLiftWorkOnslowCountyNc640Jpg from '@/assets/lawn-left-unrutted-after-lift-work-onslow-county-nc-640.jpg';
import lawnLeftUnruttedAfterLiftWorkOnslowCountyNc800Avif from '@/assets/lawn-left-unrutted-after-lift-work-onslow-county-nc-800.avif';
import lawnLeftUnruttedAfterLiftWorkOnslowCountyNc800Webp from '@/assets/lawn-left-unrutted-after-lift-work-onslow-county-nc-800.webp';
import lawnLeftUnruttedAfterLiftWorkOnslowCountyNc800Jpg from '@/assets/lawn-left-unrutted-after-lift-work-onslow-county-nc-800.jpg';
import towableLiftWorkingOverBackyardShedOnslowCountyNc400Avif from '@/assets/towable-lift-working-over-backyard-shed-onslow-county-nc-400.avif';
import towableLiftWorkingOverBackyardShedOnslowCountyNc400Webp from '@/assets/towable-lift-working-over-backyard-shed-onslow-county-nc-400.webp';
import towableLiftWorkingOverBackyardShedOnslowCountyNc400Jpg from '@/assets/towable-lift-working-over-backyard-shed-onslow-county-nc-400.jpg';
import towableLiftWorkingOverBackyardShedOnslowCountyNc640Avif from '@/assets/towable-lift-working-over-backyard-shed-onslow-county-nc-640.avif';
import towableLiftWorkingOverBackyardShedOnslowCountyNc640Webp from '@/assets/towable-lift-working-over-backyard-shed-onslow-county-nc-640.webp';
import towableLiftWorkingOverBackyardShedOnslowCountyNc640Jpg from '@/assets/towable-lift-working-over-backyard-shed-onslow-county-nc-640.jpg';
import towableLiftWorkingOverBackyardShedOnslowCountyNc800Avif from '@/assets/towable-lift-working-over-backyard-shed-onslow-county-nc-800.avif';
import towableLiftWorkingOverBackyardShedOnslowCountyNc800Webp from '@/assets/towable-lift-working-over-backyard-shed-onslow-county-nc-800.webp';
import towableLiftWorkingOverBackyardShedOnslowCountyNc800Jpg from '@/assets/towable-lift-working-over-backyard-shed-onslow-county-nc-800.jpg';
import towableLiftSetUpBehindFenceOnslowCountyNc400Avif from '@/assets/towable-lift-set-up-behind-fence-onslow-county-nc-400.avif';
import towableLiftSetUpBehindFenceOnslowCountyNc400Webp from '@/assets/towable-lift-set-up-behind-fence-onslow-county-nc-400.webp';
import towableLiftSetUpBehindFenceOnslowCountyNc400Jpg from '@/assets/towable-lift-set-up-behind-fence-onslow-county-nc-400.jpg';
import towableLiftSetUpBehindFenceOnslowCountyNc640Avif from '@/assets/towable-lift-set-up-behind-fence-onslow-county-nc-640.avif';
import towableLiftSetUpBehindFenceOnslowCountyNc640Webp from '@/assets/towable-lift-set-up-behind-fence-onslow-county-nc-640.webp';
import towableLiftSetUpBehindFenceOnslowCountyNc640Jpg from '@/assets/towable-lift-set-up-behind-fence-onslow-county-nc-640.jpg';
import towableLiftSetUpBehindFenceOnslowCountyNc800Avif from '@/assets/towable-lift-set-up-behind-fence-onslow-county-nc-800.avif';
import towableLiftSetUpBehindFenceOnslowCountyNc800Webp from '@/assets/towable-lift-set-up-behind-fence-onslow-county-nc-800.webp';
import towableLiftSetUpBehindFenceOnslowCountyNc800Jpg from '@/assets/towable-lift-set-up-behind-fence-onslow-county-nc-800.jpg';
import towableLiftReachingOverFenceToOakOnslowCountyNc400Avif from '@/assets/towable-lift-reaching-over-fence-to-oak-onslow-county-nc-400.avif';
import towableLiftReachingOverFenceToOakOnslowCountyNc400Webp from '@/assets/towable-lift-reaching-over-fence-to-oak-onslow-county-nc-400.webp';
import towableLiftReachingOverFenceToOakOnslowCountyNc400Jpg from '@/assets/towable-lift-reaching-over-fence-to-oak-onslow-county-nc-400.jpg';
import towableLiftReachingOverFenceToOakOnslowCountyNc640Avif from '@/assets/towable-lift-reaching-over-fence-to-oak-onslow-county-nc-640.avif';
import towableLiftReachingOverFenceToOakOnslowCountyNc640Webp from '@/assets/towable-lift-reaching-over-fence-to-oak-onslow-county-nc-640.webp';
import towableLiftReachingOverFenceToOakOnslowCountyNc640Jpg from '@/assets/towable-lift-reaching-over-fence-to-oak-onslow-county-nc-640.jpg';
import towableLiftReachingOverFenceToOakOnslowCountyNc800Avif from '@/assets/towable-lift-reaching-over-fence-to-oak-onslow-county-nc-800.avif';
import towableLiftReachingOverFenceToOakOnslowCountyNc800Webp from '@/assets/towable-lift-reaching-over-fence-to-oak-onslow-county-nc-800.webp';
import towableLiftReachingOverFenceToOakOnslowCountyNc800Jpg from '@/assets/towable-lift-reaching-over-fence-to-oak-onslow-county-nc-800.jpg';
import trackedLiftOnOutriggersBesideHouseOnslowCountyNc400Avif from '@/assets/tracked-lift-on-outriggers-beside-house-onslow-county-nc-400.avif';
import trackedLiftOnOutriggersBesideHouseOnslowCountyNc400Webp from '@/assets/tracked-lift-on-outriggers-beside-house-onslow-county-nc-400.webp';
import trackedLiftOnOutriggersBesideHouseOnslowCountyNc400Jpg from '@/assets/tracked-lift-on-outriggers-beside-house-onslow-county-nc-400.jpg';
import trackedLiftOnOutriggersBesideHouseOnslowCountyNc640Avif from '@/assets/tracked-lift-on-outriggers-beside-house-onslow-county-nc-640.avif';
import trackedLiftOnOutriggersBesideHouseOnslowCountyNc640Webp from '@/assets/tracked-lift-on-outriggers-beside-house-onslow-county-nc-640.webp';
import trackedLiftOnOutriggersBesideHouseOnslowCountyNc640Jpg from '@/assets/tracked-lift-on-outriggers-beside-house-onslow-county-nc-640.jpg';
import trackedLiftOnOutriggersBesideHouseOnslowCountyNc800Avif from '@/assets/tracked-lift-on-outriggers-beside-house-onslow-county-nc-800.avif';
import trackedLiftOnOutriggersBesideHouseOnslowCountyNc800Webp from '@/assets/tracked-lift-on-outriggers-beside-house-onslow-county-nc-800.webp';
import trackedLiftOnOutriggersBesideHouseOnslowCountyNc800Jpg from '@/assets/tracked-lift-on-outriggers-beside-house-onslow-county-nc-800.jpg';
import liftBoomOverTarpedRoofOnslowCountyNc400Avif from '@/assets/lift-boom-over-tarped-roof-onslow-county-nc-400.avif';
import liftBoomOverTarpedRoofOnslowCountyNc400Webp from '@/assets/lift-boom-over-tarped-roof-onslow-county-nc-400.webp';
import liftBoomOverTarpedRoofOnslowCountyNc400Jpg from '@/assets/lift-boom-over-tarped-roof-onslow-county-nc-400.jpg';
import liftBoomOverTarpedRoofOnslowCountyNc640Avif from '@/assets/lift-boom-over-tarped-roof-onslow-county-nc-640.avif';
import liftBoomOverTarpedRoofOnslowCountyNc640Webp from '@/assets/lift-boom-over-tarped-roof-onslow-county-nc-640.webp';
import liftBoomOverTarpedRoofOnslowCountyNc640Jpg from '@/assets/lift-boom-over-tarped-roof-onslow-county-nc-640.jpg';
import liftBoomOverTarpedRoofOnslowCountyNc800Avif from '@/assets/lift-boom-over-tarped-roof-onslow-county-nc-800.avif';
import liftBoomOverTarpedRoofOnslowCountyNc800Webp from '@/assets/lift-boom-over-tarped-roof-onslow-county-nc-800.webp';
import liftBoomOverTarpedRoofOnslowCountyNc800Jpg from '@/assets/lift-boom-over-tarped-roof-onslow-county-nc-800.jpg';
import tarpedRoofUnderLiftOnslowCountyNc400Avif from '@/assets/tarped-roof-under-lift-onslow-county-nc-400.avif';
import tarpedRoofUnderLiftOnslowCountyNc400Webp from '@/assets/tarped-roof-under-lift-onslow-county-nc-400.webp';
import tarpedRoofUnderLiftOnslowCountyNc400Jpg from '@/assets/tarped-roof-under-lift-onslow-county-nc-400.jpg';
import tarpedRoofUnderLiftOnslowCountyNc640Avif from '@/assets/tarped-roof-under-lift-onslow-county-nc-640.avif';
import tarpedRoofUnderLiftOnslowCountyNc640Webp from '@/assets/tarped-roof-under-lift-onslow-county-nc-640.webp';
import tarpedRoofUnderLiftOnslowCountyNc640Jpg from '@/assets/tarped-roof-under-lift-onslow-county-nc-640.jpg';
import tarpedRoofUnderLiftOnslowCountyNc800Avif from '@/assets/tarped-roof-under-lift-onslow-county-nc-800.avif';
import tarpedRoofUnderLiftOnslowCountyNc800Webp from '@/assets/tarped-roof-under-lift-onslow-county-nc-800.webp';
import tarpedRoofUnderLiftOnslowCountyNc800Jpg from '@/assets/tarped-roof-under-lift-onslow-county-nc-800.jpg';
import tallPinesOverHousesOnslowCountyNc400Avif from '@/assets/tall-pines-over-houses-onslow-county-nc-400.avif';
import tallPinesOverHousesOnslowCountyNc400Webp from '@/assets/tall-pines-over-houses-onslow-county-nc-400.webp';
import tallPinesOverHousesOnslowCountyNc400Jpg from '@/assets/tall-pines-over-houses-onslow-county-nc-400.jpg';
import tallPinesOverHousesOnslowCountyNc640Avif from '@/assets/tall-pines-over-houses-onslow-county-nc-640.avif';
import tallPinesOverHousesOnslowCountyNc640Webp from '@/assets/tall-pines-over-houses-onslow-county-nc-640.webp';
import tallPinesOverHousesOnslowCountyNc640Jpg from '@/assets/tall-pines-over-houses-onslow-county-nc-640.jpg';
import tallPinesOverHousesOnslowCountyNc800Avif from '@/assets/tall-pines-over-houses-onslow-county-nc-800.avif';
import tallPinesOverHousesOnslowCountyNc800Webp from '@/assets/tall-pines-over-houses-onslow-county-nc-800.webp';
import tallPinesOverHousesOnslowCountyNc800Jpg from '@/assets/tall-pines-over-houses-onslow-county-nc-800.jpg';
import climberAscendingLimbedTrunkOnslowCountyNc400Avif from '@/assets/climber-ascending-limbed-trunk-onslow-county-nc-400.avif';
import climberAscendingLimbedTrunkOnslowCountyNc400Webp from '@/assets/climber-ascending-limbed-trunk-onslow-county-nc-400.webp';
import climberAscendingLimbedTrunkOnslowCountyNc400Jpg from '@/assets/climber-ascending-limbed-trunk-onslow-county-nc-400.jpg';
import climberAscendingLimbedTrunkOnslowCountyNc640Avif from '@/assets/climber-ascending-limbed-trunk-onslow-county-nc-640.avif';
import climberAscendingLimbedTrunkOnslowCountyNc640Webp from '@/assets/climber-ascending-limbed-trunk-onslow-county-nc-640.webp';
import climberAscendingLimbedTrunkOnslowCountyNc640Jpg from '@/assets/climber-ascending-limbed-trunk-onslow-county-nc-640.jpg';
import climberAscendingLimbedTrunkOnslowCountyNc800Avif from '@/assets/climber-ascending-limbed-trunk-onslow-county-nc-800.avif';
import climberAscendingLimbedTrunkOnslowCountyNc800Webp from '@/assets/climber-ascending-limbed-trunk-onslow-county-nc-800.webp';
import climberAscendingLimbedTrunkOnslowCountyNc800Jpg from '@/assets/climber-ascending-limbed-trunk-onslow-county-nc-800.jpg';
import climberToppingPineBesideCraneOnslowCountyNc400Avif from '@/assets/climber-topping-pine-beside-crane-onslow-county-nc-400.avif';
import climberToppingPineBesideCraneOnslowCountyNc400Webp from '@/assets/climber-topping-pine-beside-crane-onslow-county-nc-400.webp';
import climberToppingPineBesideCraneOnslowCountyNc400Jpg from '@/assets/climber-topping-pine-beside-crane-onslow-county-nc-400.jpg';
import climberToppingPineBesideCraneOnslowCountyNc640Avif from '@/assets/climber-topping-pine-beside-crane-onslow-county-nc-640.avif';
import climberToppingPineBesideCraneOnslowCountyNc640Webp from '@/assets/climber-topping-pine-beside-crane-onslow-county-nc-640.webp';
import climberToppingPineBesideCraneOnslowCountyNc640Jpg from '@/assets/climber-topping-pine-beside-crane-onslow-county-nc-640.jpg';
import climberToppingPineBesideCraneOnslowCountyNc800Avif from '@/assets/climber-topping-pine-beside-crane-onslow-county-nc-800.avif';
import climberToppingPineBesideCraneOnslowCountyNc800Webp from '@/assets/climber-topping-pine-beside-crane-onslow-county-nc-800.webp';
import climberToppingPineBesideCraneOnslowCountyNc800Jpg from '@/assets/climber-topping-pine-beside-crane-onslow-county-nc-800.jpg';
import climberHighInToppedTreeOnslowCountyNc400Avif from '@/assets/climber-high-in-topped-tree-onslow-county-nc-400.avif';
import climberHighInToppedTreeOnslowCountyNc400Webp from '@/assets/climber-high-in-topped-tree-onslow-county-nc-400.webp';
import climberHighInToppedTreeOnslowCountyNc400Jpg from '@/assets/climber-high-in-topped-tree-onslow-county-nc-400.jpg';
import climberHighInToppedTreeOnslowCountyNc640Avif from '@/assets/climber-high-in-topped-tree-onslow-county-nc-640.avif';
import climberHighInToppedTreeOnslowCountyNc640Webp from '@/assets/climber-high-in-topped-tree-onslow-county-nc-640.webp';
import climberHighInToppedTreeOnslowCountyNc640Jpg from '@/assets/climber-high-in-topped-tree-onslow-county-nc-640.jpg';
import climberHighInToppedTreeOnslowCountyNc800Avif from '@/assets/climber-high-in-topped-tree-onslow-county-nc-800.avif';
import climberHighInToppedTreeOnslowCountyNc800Webp from '@/assets/climber-high-in-topped-tree-onslow-county-nc-800.webp';
import climberHighInToppedTreeOnslowCountyNc800Jpg from '@/assets/climber-high-in-topped-tree-onslow-county-nc-800.jpg';

/* The red oak, central Jacksonville — item 1. */
export const RED_OAK_STUMP: Photo = {
  src: redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc800Jpg,
  srcSet: `${redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc400Webp} 400w, ${redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc640Webp} 640w, ${redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc800Webp} 800w`,
  avifSrcSet: `${redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc400Avif} 400w, ${redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc640Avif} 640w, ${redOakStumpFiveFeetWideBeforeGrindingJacksonvilleNc800Avif} 800w`,
  width: 800,
  height: 600,
};
export const RED_OAK_GRINDING: Photo = {
  src: redOakStumpGrindingRootChasingJacksonvilleNc800Jpg,
  srcSet: `${redOakStumpGrindingRootChasingJacksonvilleNc400Webp} 400w, ${redOakStumpGrindingRootChasingJacksonvilleNc640Webp} 640w, ${redOakStumpGrindingRootChasingJacksonvilleNc800Webp} 800w`,
  avifSrcSet: `${redOakStumpGrindingRootChasingJacksonvilleNc400Avif} 400w, ${redOakStumpGrindingRootChasingJacksonvilleNc640Avif} 640w, ${redOakStumpGrindingRootChasingJacksonvilleNc800Avif} 800w`,
  width: 800,
  height: 600,
};

/* Resistograph traces — item 2. Wider ladder: these are read, not glanced at. */
export const RESISTOGRAPH_TRACE: Photo = {
  src: resistographTraceWaterOakHeartwoodRotJacksonvilleNc1024Jpg,
  srcSet: `${resistographTraceWaterOakHeartwoodRotJacksonvilleNc480Webp} 480w, ${resistographTraceWaterOakHeartwoodRotJacksonvilleNc768Webp} 768w, ${resistographTraceWaterOakHeartwoodRotJacksonvilleNc1024Webp} 1024w`,
  avifSrcSet: `${resistographTraceWaterOakHeartwoodRotJacksonvilleNc480Avif} 480w, ${resistographTraceWaterOakHeartwoodRotJacksonvilleNc768Avif} 768w, ${resistographTraceWaterOakHeartwoodRotJacksonvilleNc1024Avif} 1024w`,
  width: 1024,
  height: 1365,
};
export const RESISTOGRAPH_SCALE: Photo = {
  src: resistographTracePenForScaleJacksonvilleNc1024Jpg,
  srcSet: `${resistographTracePenForScaleJacksonvilleNc480Webp} 480w, ${resistographTracePenForScaleJacksonvilleNc768Webp} 768w, ${resistographTracePenForScaleJacksonvilleNc1024Webp} 1024w`,
  avifSrcSet: `${resistographTracePenForScaleJacksonvilleNc480Avif} 480w, ${resistographTracePenForScaleJacksonvilleNc768Avif} 768w, ${resistographTracePenForScaleJacksonvilleNc1024Avif} 1024w`,
  width: 1024,
  height: 1365,
};

/* Pine health — item 4. */
export const PITCH_TUBES: Photo = {
  src: southernPineBeetlePitchTubesOnslowCountyNc600Jpg,
  srcSet: `${southernPineBeetlePitchTubesOnslowCountyNc400Webp} 400w, ${southernPineBeetlePitchTubesOnslowCountyNc600Webp} 600w`,
  avifSrcSet: `${southernPineBeetlePitchTubesOnslowCountyNc400Avif} 400w, ${southernPineBeetlePitchTubesOnslowCountyNc600Avif} 600w`,
  width: 600,
  height: 800,
};
export const RICHLANDS_CRACKED_LIMB: Photo = {
  src: windCrackedPineLimbOverHouseRichlandsNc800Jpg,
  srcSet: `${windCrackedPineLimbOverHouseRichlandsNc400Webp} 400w, ${windCrackedPineLimbOverHouseRichlandsNc640Webp} 640w, ${windCrackedPineLimbOverHouseRichlandsNc800Webp} 800w`,
  avifSrcSet: `${windCrackedPineLimbOverHouseRichlandsNc400Avif} 400w, ${windCrackedPineLimbOverHouseRichlandsNc640Avif} 640w, ${windCrackedPineLimbOverHouseRichlandsNc800Avif} 800w`,
  width: 800,
  height: 600,
};
export const RICHLANDS_CANOPY_LIMB: Photo = {
  src: crackedPineLimbCanopyInspectionRichlandsNc800Jpg,
  srcSet: `${crackedPineLimbCanopyInspectionRichlandsNc400Webp} 400w, ${crackedPineLimbCanopyInspectionRichlandsNc640Webp} 640w, ${crackedPineLimbCanopyInspectionRichlandsNc800Webp} 800w`,
  avifSrcSet: `${crackedPineLimbCanopyInspectionRichlandsNc400Avif} 400w, ${crackedPineLimbCanopyInspectionRichlandsNc640Avif} 640w, ${crackedPineLimbCanopyInspectionRichlandsNc800Avif} 800w`,
  width: 800,
  height: 1067,
};

/* Heartwood rot, Surf City — item 5. */
export const SURF_CITY_HOLLOW: Photo = {
  src: heartwoodRotHollowOakTrunkSurfCityNc800Jpg,
  srcSet: `${heartwoodRotHollowOakTrunkSurfCityNc400Webp} 400w, ${heartwoodRotHollowOakTrunkSurfCityNc640Webp} 640w, ${heartwoodRotHollowOakTrunkSurfCityNc800Webp} 800w`,
  avifSrcSet: `${heartwoodRotHollowOakTrunkSurfCityNc400Avif} 400w, ${heartwoodRotHollowOakTrunkSurfCityNc640Avif} 640w, ${heartwoodRotHollowOakTrunkSurfCityNc800Avif} 800w`,
  width: 800,
  height: 1067,
};
export const SURF_CITY_STUMP: Photo = {
  src: heartwoodRotOakStumpSurfCityNc800Jpg,
  srcSet: `${heartwoodRotOakStumpSurfCityNc400Webp} 400w, ${heartwoodRotOakStumpSurfCityNc640Webp} 640w, ${heartwoodRotOakStumpSurfCityNc800Webp} 800w`,
  avifSrcSet: `${heartwoodRotOakStumpSurfCityNc400Avif} 400w, ${heartwoodRotOakStumpSurfCityNc640Avif} 640w, ${heartwoodRotOakStumpSurfCityNc800Avif} 800w`,
  width: 800,
  height: 1067,
};

/* Beulaville barn and canopy breaks — item 6. */
export const BARN_DAMAGE: Photo = {
  src: treeThroughBarnRoofBeulavilleNc800Jpg,
  srcSet: `${treeThroughBarnRoofBeulavilleNc400Webp} 400w, ${treeThroughBarnRoofBeulavilleNc640Webp} 640w, ${treeThroughBarnRoofBeulavilleNc800Webp} 800w`,
  avifSrcSet: `${treeThroughBarnRoofBeulavilleNc400Avif} 400w, ${treeThroughBarnRoofBeulavilleNc640Avif} 640w, ${treeThroughBarnRoofBeulavilleNc800Avif} 800w`,
  width: 800,
  height: 600,
};
export const BARN_CRANE: Photo = {
  src: craneSetUpOverDamagedBarnBeulavilleNc800Jpg,
  srcSet: `${craneSetUpOverDamagedBarnBeulavilleNc400Webp} 400w, ${craneSetUpOverDamagedBarnBeulavilleNc640Webp} 640w, ${craneSetUpOverDamagedBarnBeulavilleNc800Webp} 800w`,
  avifSrcSet: `${craneSetUpOverDamagedBarnBeulavilleNc400Avif} 400w, ${craneSetUpOverDamagedBarnBeulavilleNc640Avif} 640w, ${craneSetUpOverDamagedBarnBeulavilleNc800Avif} 800w`,
  width: 800,
  height: 600,
};
export const BARN_CLIMBER: Photo = {
  src: climberInFallenTreeOnBarnBeulavilleNc800Jpg,
  srcSet: `${climberInFallenTreeOnBarnBeulavilleNc400Webp} 400w, ${climberInFallenTreeOnBarnBeulavilleNc640Webp} 640w, ${climberInFallenTreeOnBarnBeulavilleNc800Webp} 800w`,
  avifSrcSet: `${climberInFallenTreeOnBarnBeulavilleNc400Avif} 400w, ${climberInFallenTreeOnBarnBeulavilleNc640Avif} 640w, ${climberInFallenTreeOnBarnBeulavilleNc800Avif} 800w`,
  width: 800,
  height: 1067,
};
export const BARN_LIFT_OUT: Photo = {
  src: craneLiftingTreeSectionOffBarnBeulavilleNc800Jpg,
  srcSet: `${craneLiftingTreeSectionOffBarnBeulavilleNc400Webp} 400w, ${craneLiftingTreeSectionOffBarnBeulavilleNc640Webp} 640w, ${craneLiftingTreeSectionOffBarnBeulavilleNc800Webp} 800w`,
  avifSrcSet: `${craneLiftingTreeSectionOffBarnBeulavilleNc400Avif} 400w, ${craneLiftingTreeSectionOffBarnBeulavilleNc640Avif} 640w, ${craneLiftingTreeSectionOffBarnBeulavilleNc800Avif} 800w`,
  width: 800,
  height: 1067,
};
export const BROKEN_LIMB_CANOPY: Photo = {
  src: stormBrokenLimbHangingInCanopyOnslowCountyNc800Jpg,
  srcSet: `${stormBrokenLimbHangingInCanopyOnslowCountyNc400Webp} 400w, ${stormBrokenLimbHangingInCanopyOnslowCountyNc640Webp} 640w, ${stormBrokenLimbHangingInCanopyOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${stormBrokenLimbHangingInCanopyOnslowCountyNc400Avif} 400w, ${stormBrokenLimbHangingInCanopyOnslowCountyNc640Avif} 640w, ${stormBrokenLimbHangingInCanopyOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1067,
};
export const SPLIT_LIMB_CANOPY: Photo = {
  src: splitPineLimbInCanopyOnslowCountyNc800Jpg,
  srcSet: `${splitPineLimbInCanopyOnslowCountyNc400Webp} 400w, ${splitPineLimbInCanopyOnslowCountyNc640Webp} 640w, ${splitPineLimbInCanopyOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${splitPineLimbInCanopyOnslowCountyNc400Avif} 400w, ${splitPineLimbInCanopyOnslowCountyNc640Avif} 640w, ${splitPineLimbInCanopyOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1067,
};

/* Equipment — item 9. */
export const LIFT_TO_PINE: Photo = {
  src: spiderLiftBoomExtendedToPineOnslowCountyNc800Jpg,
  srcSet: `${spiderLiftBoomExtendedToPineOnslowCountyNc400Webp} 400w, ${spiderLiftBoomExtendedToPineOnslowCountyNc640Webp} 640w, ${spiderLiftBoomExtendedToPineOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${spiderLiftBoomExtendedToPineOnslowCountyNc400Avif} 400w, ${spiderLiftBoomExtendedToPineOnslowCountyNc640Avif} 640w, ${spiderLiftBoomExtendedToPineOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1067,
};
export const LIFT_ON_LAWN: Photo = {
  src: spiderLiftTrackedBaseOnLawnOnslowCountyNc800Jpg,
  srcSet: `${spiderLiftTrackedBaseOnLawnOnslowCountyNc400Webp} 400w, ${spiderLiftTrackedBaseOnLawnOnslowCountyNc640Webp} 640w, ${spiderLiftTrackedBaseOnLawnOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${spiderLiftTrackedBaseOnLawnOnslowCountyNc400Avif} 400w, ${spiderLiftTrackedBaseOnLawnOnslowCountyNc640Avif} 640w, ${spiderLiftTrackedBaseOnLawnOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 600,
};
export const LAWN_UNRUTTED: Photo = {
  src: lawnLeftUnruttedAfterLiftWorkOnslowCountyNc800Jpg,
  srcSet: `${lawnLeftUnruttedAfterLiftWorkOnslowCountyNc400Webp} 400w, ${lawnLeftUnruttedAfterLiftWorkOnslowCountyNc640Webp} 640w, ${lawnLeftUnruttedAfterLiftWorkOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${lawnLeftUnruttedAfterLiftWorkOnslowCountyNc400Avif} 400w, ${lawnLeftUnruttedAfterLiftWorkOnslowCountyNc640Avif} 640w, ${lawnLeftUnruttedAfterLiftWorkOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1067,
};
export const TOWABLE_OVER_SHED: Photo = {
  src: towableLiftWorkingOverBackyardShedOnslowCountyNc800Jpg,
  srcSet: `${towableLiftWorkingOverBackyardShedOnslowCountyNc400Webp} 400w, ${towableLiftWorkingOverBackyardShedOnslowCountyNc640Webp} 640w, ${towableLiftWorkingOverBackyardShedOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${towableLiftWorkingOverBackyardShedOnslowCountyNc400Avif} 400w, ${towableLiftWorkingOverBackyardShedOnslowCountyNc640Avif} 640w, ${towableLiftWorkingOverBackyardShedOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1067,
};
export const TOWABLE_BEHIND_FENCE: Photo = {
  src: towableLiftSetUpBehindFenceOnslowCountyNc800Jpg,
  srcSet: `${towableLiftSetUpBehindFenceOnslowCountyNc400Webp} 400w, ${towableLiftSetUpBehindFenceOnslowCountyNc640Webp} 640w, ${towableLiftSetUpBehindFenceOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${towableLiftSetUpBehindFenceOnslowCountyNc400Avif} 400w, ${towableLiftSetUpBehindFenceOnslowCountyNc640Avif} 640w, ${towableLiftSetUpBehindFenceOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 600,
};
export const TOWABLE_OVER_FENCE: Photo = {
  src: towableLiftReachingOverFenceToOakOnslowCountyNc800Jpg,
  srcSet: `${towableLiftReachingOverFenceToOakOnslowCountyNc400Webp} 400w, ${towableLiftReachingOverFenceToOakOnslowCountyNc640Webp} 640w, ${towableLiftReachingOverFenceToOakOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${towableLiftReachingOverFenceToOakOnslowCountyNc400Avif} 400w, ${towableLiftReachingOverFenceToOakOnslowCountyNc640Avif} 640w, ${towableLiftReachingOverFenceToOakOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 600,
};
export const TRACKED_OUTRIGGERS: Photo = {
  src: trackedLiftOnOutriggersBesideHouseOnslowCountyNc800Jpg,
  srcSet: `${trackedLiftOnOutriggersBesideHouseOnslowCountyNc400Webp} 400w, ${trackedLiftOnOutriggersBesideHouseOnslowCountyNc640Webp} 640w, ${trackedLiftOnOutriggersBesideHouseOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${trackedLiftOnOutriggersBesideHouseOnslowCountyNc400Avif} 400w, ${trackedLiftOnOutriggersBesideHouseOnslowCountyNc640Avif} 640w, ${trackedLiftOnOutriggersBesideHouseOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 600,
};
export const BOOM_OVER_TARP: Photo = {
  src: liftBoomOverTarpedRoofOnslowCountyNc800Jpg,
  srcSet: `${liftBoomOverTarpedRoofOnslowCountyNc400Webp} 400w, ${liftBoomOverTarpedRoofOnslowCountyNc640Webp} 640w, ${liftBoomOverTarpedRoofOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${liftBoomOverTarpedRoofOnslowCountyNc400Avif} 400w, ${liftBoomOverTarpedRoofOnslowCountyNc640Avif} 640w, ${liftBoomOverTarpedRoofOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1067,
};
export const TARPED_ROOF: Photo = {
  src: tarpedRoofUnderLiftOnslowCountyNc800Jpg,
  srcSet: `${tarpedRoofUnderLiftOnslowCountyNc400Webp} 400w, ${tarpedRoofUnderLiftOnslowCountyNc640Webp} 640w, ${tarpedRoofUnderLiftOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${tarpedRoofUnderLiftOnslowCountyNc400Avif} 400w, ${tarpedRoofUnderLiftOnslowCountyNc640Avif} 640w, ${tarpedRoofUnderLiftOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1067,
};

/* Removal page, pines and climbers — item 9. */
export const TALL_PINES_OVER_HOUSES: Photo = {
  src: tallPinesOverHousesOnslowCountyNc800Jpg,
  srcSet: `${tallPinesOverHousesOnslowCountyNc400Webp} 400w, ${tallPinesOverHousesOnslowCountyNc640Webp} 640w, ${tallPinesOverHousesOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${tallPinesOverHousesOnslowCountyNc400Avif} 400w, ${tallPinesOverHousesOnslowCountyNc640Avif} 640w, ${tallPinesOverHousesOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 600,
};
export const CLIMBER_ASCENDING: Photo = {
  src: climberAscendingLimbedTrunkOnslowCountyNc800Jpg,
  srcSet: `${climberAscendingLimbedTrunkOnslowCountyNc400Webp} 400w, ${climberAscendingLimbedTrunkOnslowCountyNc640Webp} 640w, ${climberAscendingLimbedTrunkOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${climberAscendingLimbedTrunkOnslowCountyNc400Avif} 400w, ${climberAscendingLimbedTrunkOnslowCountyNc640Avif} 640w, ${climberAscendingLimbedTrunkOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1352,
};
export const CLIMBER_TOPPING_PINE: Photo = {
  src: climberToppingPineBesideCraneOnslowCountyNc800Jpg,
  srcSet: `${climberToppingPineBesideCraneOnslowCountyNc400Webp} 400w, ${climberToppingPineBesideCraneOnslowCountyNc640Webp} 640w, ${climberToppingPineBesideCraneOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${climberToppingPineBesideCraneOnslowCountyNc400Avif} 400w, ${climberToppingPineBesideCraneOnslowCountyNc640Avif} 640w, ${climberToppingPineBesideCraneOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1699,
};
export const CLIMBER_TOPPED_TREE: Photo = {
  src: climberHighInToppedTreeOnslowCountyNc800Jpg,
  srcSet: `${climberHighInToppedTreeOnslowCountyNc400Webp} 400w, ${climberHighInToppedTreeOnslowCountyNc640Webp} 640w, ${climberHighInToppedTreeOnslowCountyNc800Webp} 800w`,
  avifSrcSet: `${climberHighInToppedTreeOnslowCountyNc400Avif} 400w, ${climberHighInToppedTreeOnslowCountyNc640Avif} 640w, ${climberHighInToppedTreeOnslowCountyNc800Avif} 800w`,
  width: 800,
  height: 1352,
};
